name: irc

on: [push]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: IRC notification
    steps:
      - name: Format message
        id: message
        env:
          ACTOR: ${{ github.actor }}
          COMMIT_MSG: ${{ github.event.commits[0].message }}
          COMMIT_URL: ${{ github.event.commits[0].url }}
        run: |
          FIRST_LINE=$(printf '%s\n' "$COMMIT_MSG" | head -n 1)
          echo "message=$ACTOR pushed $FIRST_LINE $COMMIT_URL" >> "$GITHUB_OUTPUT"
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#modaudio'
          nickname: modaudio-bot
          message: ${{ steps.message.outputs.message }}
